// Subset CJK UI fonts.
//
// The lv_font_zh_* fonts are generated by tools/gen_zh_font.js from a CJK TTF
// and cover ASCII (0x20-0x7F) plus exactly the Chinese glyphs the UI uses, so
// both English and Simplified Chinese render from one font with no runtime
// font engine. The font data lives in assets/fonts/lv_font_zh_<size>.c.
#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(lv_font_zh_14);
LV_FONT_DECLARE(lv_font_zh_16);
LV_FONT_DECLARE(lv_font_zh_20);
