// UI localisation tables.
//
// NOTE: the Chinese characters in kZh below are the *only* non-ASCII content
// in this file on purpose — tools/gen_zh_font.js scans this file for every
// non-ASCII codepoint and subsets the CJK font to exactly those glyphs. Keep
// all comments ASCII-only, and regenerate the fonts after editing kZh.
#include "i18n.h"

namespace jusiai {
namespace {

Lang g_lang = Lang::Zh;

constexpr int kCount = static_cast<int>(Msg::Count_);

// Simplified Chinese — the default language.
const char* const kZh[kCount] = {
    "巨思 AI 助手",             // AppTitle
    "内容由 AI 生成",           // Disclaimer
    "就绪",                     // StatusReady
    "点击呼叫按钮开始通话",     // HintTapToBegin
    "正在创建房间...",          // StatusCreatingRoom
    "正在连接...",              // StatusConnecting
    "正在唤起 AI 助手...",      // StatusWakingAgent
    "聆听中",                   // StatusListening
    "正在结束通话...",          // StatusEndingCall
    "通话已结束",               // StatusCallEnded
    "AI 助手已离开房间",        // HintAgentLeft
    "AI 助手未响应",            // ErrAgentNoResponse
    "请重试",                   // HintTryAgain
    "连接已断开",               // ErrDisconnected
    "网络连接已丢失",           // HintConnectionLost
    "无法创建房间",             // ErrCreateRoom
    "无法连接",                 // ErrConnect
    "无法连接到媒体服务器",     // HintMediaServer
    "无法发布音频",             // ErrPublishAudio
    "无法启动 AI 助手",         // ErrStartAgent
};

const char* const kEn[kCount] = {
    "JUSI AI Assistant",                // AppTitle
    "Content generated by AI",          // Disclaimer
    "Ready",                            // StatusReady
    "Tap the call button to begin",     // HintTapToBegin
    "Creating room...",                 // StatusCreatingRoom
    "Connecting...",                    // StatusConnecting
    "Waking up the AI assistant...",    // StatusWakingAgent
    "Listening",                        // StatusListening
    "Ending the call...",               // StatusEndingCall
    "Call ended",                       // StatusCallEnded
    "The AI assistant left the room",   // HintAgentLeft
    "The AI assistant did not respond", // ErrAgentNoResponse
    "Please try again",                 // HintTryAgain
    "Disconnected",                     // ErrDisconnected
    "The connection was lost",          // HintConnectionLost
    "Could not create a room",          // ErrCreateRoom
    "Could not connect",                // ErrConnect
    "Failed to reach the media server", // HintMediaServer
    "Could not publish audio",          // ErrPublishAudio
    "Could not start the AI assistant", // ErrStartAgent
};

}  // namespace

Lang lang_from_string(const std::string& s) {
  // English only when the tag clearly starts with "en"; otherwise Chinese.
  if (s.size() >= 2 && (s[0] == 'e' || s[0] == 'E') &&
      (s[1] == 'n' || s[1] == 'N')) {
    return Lang::En;
  }
  return Lang::Zh;
}

void set_language(Lang lang) { g_lang = lang; }
Lang current_language() { return g_lang; }

const char* tr(Msg m) {
  const int i = static_cast<int>(m);
  if (i < 0 || i >= kCount) return "";
  return (g_lang == Lang::En ? kEn : kZh)[i];
}

}  // namespace jusiai
