// Tiny UI localisation layer. The interface text exists in Simplified Chinese
// (the default) and English; tr() returns the string for the currently
// selected language. The set of translatable messages is small and fixed.
#pragma once

#include <string>

namespace jusiai {

enum class Lang { Zh, En };

// Every translatable UI string. Keep this in sync with the kZh / kEn tables
// in i18n.cpp (same order).
enum class Msg {
  AppTitle,            // window / header title
  Disclaimer,          // "content generated by AI" footer
  StatusReady,         // idle status
  HintTapToBegin,      // idle hint
  StatusCreatingRoom,  // creating the device-API room
  StatusConnecting,    // joining LiveKit
  StatusWakingAgent,   // dispatching the AI agent
  StatusListening,     // agent online, call live
  StatusEndingCall,    // tearing the call down
  StatusCallEnded,     // agent left normally
  HintAgentLeft,       // detail for StatusCallEnded
  ErrAgentNoResponse,  // agent join timed out
  HintTryAgain,        // generic retry hint
  ErrDisconnected,     // transport dropped
  HintConnectionLost,  // detail for ErrDisconnected
  ErrCreateRoom,       // device-API room creation failed
  ErrConnect,          // LiveKit connect failed
  HintMediaServer,     // detail for ErrConnect
  ErrPublishAudio,     // publishing the mic track failed
  ErrStartAgent,       // dispatching the AI agent failed
  Count_
};

// Parse a language tag ("zh", "zh-CN", "en", "en-US", ...). Anything that is
// not clearly English resolves to Simplified Chinese — the default.
Lang lang_from_string(const std::string& s);

// Select the active language. Call once at start-up, before any tr() use.
void set_language(Lang lang);
Lang current_language();

// The message text in the active language. Never returns null.
const char* tr(Msg m);

}  // namespace jusiai
